### ISSUE TITLE
Cant get source info

### ISSUE THREAD

**Issue by Quantum-Codes** [scrazzz/imgbbpy#1]
![chrome_screenshot_1661875827838](https://user-images.githubusercontent.com/87054411/187487396-47bbc211-0e07-47a3-8b99-84cad0246695.png)

I was trying to upload graphs generated by matplot lib both in svg
Edit: png works

My code: https://replit.com/@QuantumCodes/graph-uploader#upload.py
How to fix this?

**Comment by Quantum-Codes** [comment]
```python
os.system("pip install imgbbpy")
token = os.environ['Token']
files = os.listdir("images")

import imgbbpy

client = imgbbpy.SyncClient(token)
image = client.upload(file=f"images/{files[0]}")
print(image.url)
```

**Comment by Quantum-Codes** [comment]
Ok imgbb doesn't support svg..
Supported type: JPG, PNG, BMP, GIF, TIF, WEBP, HEIC, and PDF.

**Comment by scrazzz** [comment]
Hello, thanks for opening this issue. I'll make sure to add a statement in the error code to check whether the content is supported by imgbb.

**Comment by Quantum-Codes** [comment]
Np!
Just a question: is it possible to replace the  image through API?

I require a system where the image changes every week but the link stays the same. So is it possible to replace the image through api? It is possible by the frontend

**Comment by scrazzz** [comment]
> Np! Just a question: is it possible to replace the image through API?
> 
> I require a system where the image changes every week but the link stays the same. So is it possible to replace the image through api? It is possible by the frontend

Sorry, I don't think that's possible. Imgbb assigns a unique value to the link as far as I know.

**Comment by Quantum-Codes** [comment]
Ok thank you!
